### PR TITLE
test: failing without annotations

### PR DESCRIPTION
**Pull request by blaggacao**
This tests exposes the edge case issue with the current implementation

### CODE REVIEW

**Comment by blaggacao** [comment]
... or I hope so :wink: 

Locally on post mortem I get this:
```python
(Pdb++) self.namespace
mappingproxy({'__module__': 'dodoo.configs.db', '__doc__': None, 'to_dict': <function to_dict at 0x7fe263310d40>})
```

```bash
poetry env info

Virtualenv
Python:         3.7.5
Implementation: CPython
Path:           /home/blaggacao/.cache/pypoetry/virtualenvs/dodoo-sbhREzF6-py3.7
Valid:          True

System
Platform: linux
OS:       posix
Python:   /home/blaggacao/.pyenv/versions/3.7.5
```

**Comment by blaggacao** [comment]
Test case for #14

**Comment by blaggacao** [comment]
@Fatal1ty Maybe you could quickly chekc if this merits a `1.12` release? :stuck_out_tongue_winking_eye:

**Comment by Fatal1ty** [comment]
I fixed it by myself. Thanks you @blaggacao

**Pull request closed without merging**
