### PR TITLE
Fix "<locals>" in generated code

### LINKED ISSUE #182: The types defined inside the function result in syntactically invalid generated code
* mashumaro version: 3.11
* Python version: 3.12
* Operating System: macOS 14.1

### Description

If someone puts dataclasses or other types inside a function, a syntax error will occur. This problem first reported in the following pull requests:
* https://github.com/Fatal1ty/mashumaro/pull/180
* https://github.com/Fatal1ty/mashumaro/pull/181

### What I Did

This code:

```python
def foobar():
    @dataclass
    class Foo:
        foo: int

    @dataclass
    class Bar(DataClassDictMixin):
        foo: Foo

foobar()
```

leads to this exception:

```python
raise MissingField('foo',__main__.foobar.<locals>.Foo,cls) from None
```

There is the `type_name` helper function that may return a string containing `<locals>` if the type is defined in a function scope. This string may then be used inside the generated code. We need to come up with a general solution because `type_name` is used widely across all the code base. One way would be a wrapper for `type_name` helper in `CodeBuilder`:

```python
def type_name(self, typ, *args, **kwargs) -> str:
    name = type_name(typ, *args, **kwargs)
    if "<locals>" in name:
        name = clean_id(name)
        self.ensure_object_imported(typ, name)
    return name
```

### PR DESCRIPTION
**Pull request by vovanbo**
Fix #182. Another try to fix this bug with simple decoration of `type_name` method.

### CODE REVIEW

**Comment by mishamsk** [comment]
the reason why I didn't use decorator in #180 (which also fixes this issue + adds tests) is because decorators are a bit of magic and less explicit. They may even not work in some cases, e.g. we compile a project depending on mashumaro using Nuitka, which sometimes struggles with overly "magical" stuff.

What I didn't do in my PR is adding a schema test. Maybe it would make sense to merge the test from this PR with the change from mine?

Anyways, we need @Fatal1ty to return from vacation;-)

**Comment by Fatal1ty** [comment]
> Anyways, we need @Fatal1ty to return from vacation;-)

I promise to get back to the business this weekend 👀

**Comment by vovanbo** [comment]
Is this pull request still required? #182 is fixed now as i see. When new version of mashumaro will be released?

**Comment by Fatal1ty** [comment]
> Is this pull request still required? #182 is fixed now as i see.

#182 is fixed but it was all about serialization / deserialization. The same issue still persist in JSON Schema generation which you discovered in #181. I need more time to think through possible solutions. Probably, I'll reopen and accept #181.

As @mishamsk pointed out, it'll be worth merging the tests from here, I'll do it after.

> When new version of mashumaro will be released?

Right after getting this and #187 done if nothing new comes up :)

**Comment by Fatal1ty** [comment]
The fix for discriminators was easy to implement #189. I believe local types are now fully supported.

**Pull request closed without merging**
