### PR TITLE
Enable use of hooks in superclasses

### PR DESCRIPTION
**Pull request by gshank**
Our project implements common functionality in a mixin class that we include in hundreds of classes. We need to be able to supply hooks in our mixin class that work in the subclassses. The __dict__ attribute that is used to find the callouts does not find superclass methods.

### CODE REVIEW

**Comment by Fatal1ty** [comment]
Hi @gshank. I haven't thought about this usage scenario, but it does take place, obviously. But I think for performance reasons it would be better not to call the hooks all the time in case a subclass doesn't have ones. We need to check where the hook is declared and call it only if it takes a place not in `DataClassDictMixin`. If you don't need this feature right now I'll find time to implement it by myself.

**Comment by gshank** [comment]
I changed it to check for the existence of a method using 'callable', but then the methods in DataClassDictMixin had to be removed because it was finding those.

**Comment by Fatal1ty** [comment]
> but then the methods in DataClassDictMixin had to be removed because it was finding those.

It's bad because it removes the ability to see hints in the IDE that helps you to redeclare the hooks. Anyway, I'm almost ready to finish my own implementation with tests. Just give me some time and I'll release a new version.

**Comment by Fatal1ty** [comment]
Implemented in 1.22

**Pull request closed without merging**
