### PR TITLE
Add support for union types

### PR DESCRIPTION
**Pull request by gshank**
We've tested this in our project which uses a lot of Union types and it works well.

### CODE REVIEW

**Comment by Fatal1ty** [comment]
Hi @gshank. I looked at your code and found some problems.

The declaration of the `resolve_union` function on every call of `from_dict` and `to_dict` has a huge impact on performance. I was going to add support for Unions through constructing a method in the class namespace.

And we have to accept that `isinstance` isn't the best way to check complex types like generics of generics. Honestly I don't know how to make this better without true recursive validation, so this simple way might be a compromise.

**Comment by gshank** [comment]
The 'resolve_union' call doesn't impact performance unless there's a union, does it? How would a method in the class namespace be different? You still have to leave resolution of the type until calling time, since you don't know what it is.

**Comment by Fatal1ty** [comment]
If a field declared as `Union` each call of the `from_dict` or `to_dict` will create a new `resolve_union` that will be garbage collected after the `from_dict` or `to_dict` finished.

**Comment by gshank** [comment]
Why would it be garbage collected? It's just code in the existing to_dict and from_dict calls.
`def to_dict(self, use_bytes=False, use_enum=False, use_datetime=False):
    kwargs = {}
    try:
        field_name = 'initial'
        field_name = 'name'
        value = getattr(self, 'name')
        if value is None:
            kwargs['name'] = None
        else:
            kwargs['name'] = value
        field_name = 'status'
        value = getattr(self, 'status')
        if value is None:
            kwargs['status'] = None
        else:
            if '__main__' not in globals():
                import __main__
            else:
                global __main__
            def resolve_union(value):
                if isinstance(value, __main__.RunStatus):
                    try:
                        return value._serialize()
                    except (TypeError, AttributeError, ValueError, LookupError) as e:
                        pass
                if isinstance(value, __main__.TestStatus):
                    try:
                        return value._serialize()
                    except (TypeError, AttributeError, ValueError, LookupError) as e:
                        pass
                if isinstance(value, __main__.FreshnessStatus):
                    try:
                        return value._serialize()
                    except (TypeError, AttributeError, ValueError, LookupError) as e:
                        pass
                raise ValueError(f"Union value ({value}) for status could not be encoded using types (__main__.RunStatus, __main__.TestStatus, __main__.FreshnessStatus)")
            kwargs['status'] = resolve_union(value)
    except Exception as exc:
        raise ValueError(f"to_dict failed handling field '{field_name}': {str(exc)}")
    return self.__post_serialize__(kwargs)
`

**Comment by Fatal1ty** [comment]
@gshank because it’s how Python works :)

https://stackoverflow.com/questions/14055843/what-is-the-performance-overhead-of-nested-functions

**Comment by gshank** [comment]
So you want the function to be created in the class namespace, not embedded in to_dict/from_dict.

**Comment by Fatal1ty** [comment]
JFYI, Unions are now available in 1.24

**Comment by Fatal1ty** [comment]
Thank you for this pull request anyway!

**Pull request closed without merging**
