### PR TITLE
Fix handling Annotated with unhashable metadata

### LINKED ISSUE #133: collections.OrderedDict is not hashable
* mashumaro version: 3.8.1
* Python version: 3.11 / 3.10
* Operating System: Ubuntu 20.04

### Description

1. Try to run the following code
2. it keeps showing `TypeError: unhashable type: 'collections.OrderedDict'`, but the readme shows it supports this type

### What I Did

```python
import json
from enum import Enum
from typing import List, Any, Union, Generic, TypeVar, Tuple, cast, Optional, Annotated, OrderedDict, Type
import typing
import collections
from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, DataClassJsonMixin
from mashumaro.mixins.json import DataClassJSONMixin
from mashumaro.types import SerializationStrategy



def kwtypes(**kwargs) -> OrderedDict[str, Type]:
    """
    This is a small helper function to convert the keyword arguments to an OrderedDict of types.

    .. code-block:: python

        kwtypes(a=int, b=str)
    """
    d = collections.OrderedDict()
    for k, v in kwargs.items():
        d[k] = v
    return d

@dataclass
class test(DataClassJSONMixin):
    b: typing.List[Annotated[int, "parquet"]]
    c: typing.Dict[str, Annotated[int, kwtypes(Name=str, Age=int)]]
```

Thanks for the help!

### PR DESCRIPTION
**Pull request by Fatal1ty**
Closes #133

### CODE REVIEW

**Comment by hhcs9527** [comment]
Does the new release only work in python version >= 3.9?

**Comment by Fatal1ty** [comment]
> Does the new release only work in python version >= 3.9?

No, why do you ask? :)

**Comment by hhcs9527** [comment]
I tried to run the following code in python 3.8 version
```python
import json
from enum import Enum
from typing import List, Any, Union, Generic, TypeVar, Tuple, cast, Optional, OrderedDict, Type
from typing_extensions import Annotated
import typing
import collections
from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, DataClassJsonMixin
from mashumaro.mixins.json import DataClassJSONMixin
from mashumaro.types import SerializationStrategy



def kwtypes(**kwargs) -> OrderedDict[str, Type]:
    """
    This is a small helper function to convert the keyword arguments to an OrderedDict of types.

    .. code-block:: python

        kwtypes(a=int, b=str)
    """
    d = collections.OrderedDict()
    for k, v in kwargs.items():
        d[k] = v
    return d

@dataclass
class test(DataClassJSONMixin):
    b: typing.List[Annotated[int, "parquet"]]
    c: typing.Dict[str, Annotated[int, kwtypes(Name=str, Age=int)]]

```


it still shows `TypeError: unhashable type: 'collections.OrderedDict'`, however, it works with python version >= 3.9

Do you know why?

Thanks for the help.

**Comment by Fatal1ty** [comment]
@hhcs9527

I'm sorry you stumbled over this issue. Thank you for the reproducible code, I added it to the following issue:
* #138 

You can expect a 3.9.1 patch this week.

**Comment by Fatal1ty** [comment]
@hhcs9527 I couldn't do it last week, but now 3.9.1 is ready:
* https://github.com/Fatal1ty/mashumaro/releases/tag/v3.9.1

**Pull request merged**
